spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(A1t7AdOABATK9+kChWjQPNWHUI7+ZcSIrfiU55wVRIi1T398DSZGfwJNfQ5TTT4jKvP3tWUxyvHfwutqKR8GqXdoXQp/VRH1CCWdou9XX4aL2M05NrU9pDkhKwD02bF1)
    username: ENC(3R3peZ1WUtJoyusdnopaHQ==)
    password: ENC(pUlV/EthFNNw5AL6W/B3DuJZ7Y4YM765HgWKDJlbwpw=)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(3Awt+EuHWrX6PprLbTaZ9iFA2u6eeK1K)
    password: ENC(ICmyTnIrKdOVc9jripUeYyV8pDyh2iBj8VXWa2ukTwc=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  #redis
  data:
    redis:
      host: ENC(wUwgO6KDUItae11dZ/iEbN0UZi0MrGmbZJ+6J3rU77Jor0poeUqa3ap4plO9yEXVlex9t3YFZ9GBIHQcyYnUqF+E9wcr8/Z1)
      port: 6379

# swagger
springdoc:
  packages-to-scan: com.meowzip.apiserver
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true

# encryption
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
