spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(MBlVmWRNkaYIQ6L3SN6nGg2FNYdFSOr6KxFhm7j1rpyZfrEW5vAyUgaEkbgrsQELhpbzt6gMrO2I5LTRfL/OyCN7DDktDo9ZNDhASxzn5k9c6JRsbSZVX0uV7sdb3DNP)
    username: ENC(qqvaQgGSLefuc0xcPSmpCA==)
    password: ENC(y/xQTrJj1+F5Nezvd28d2q4GydDL5p+UM4l59mPgx8w=)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# swagger
springdoc:
  packages-to-scan: com.meowzip.apiserver
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true

# encryption
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
