spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(A1t7AdOABATK9+kChWjQPNWHUI7+ZcSIrfiU55wVRIi1T398DSZGfwJNfQ5TTT4jKvP3tWUxyvHfwutqKR8GqXdoXQp/VRH1CCWdou9XX4aL2M05NrU9pDkhKwD02bF1)
    username: ENC(3R3peZ1WUtJoyusdnopaHQ==)
    password: ENC(pUlV/EthFNNw5AL6W/B3DuJZ7Y4YM765HgWKDJlbwpw=)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      jdbc:
        time_zone: Asia/Seoul
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(r8lCAtY2iuRV2plqd+2v3SZ4fABqQaAH)
    password: ENC(2yM8AvckUVZSNFiDS1LyR4ftXkaRpdoih/gFfA+bdIg=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            required: true

  #redis
  data:
    redis:
      host: ENC(zF2o5/26Cdhk08Lhb0naXG8tDn/Rs4v6dsZmqwIbbBA3ZYpVKFVn9+nykQZIYUVq+dveQD3BFXTfC/QTCOUkBWc39iBpuchp)
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(ifJa29xJ9iMVgbjykH7XlHbfAEbRzSjz0Hnt3L4+sD7T1ed3RhvpBcOlD263ahYPwuEr4glUB2TdGF2qz6Z+pbCykZ+DHv1H6/Xqvnz1lXjpoH0N02GMdg==)
            client-secret: ENC(0hDth9wIbqFlZHin2A2cjSTgMAElTlNy1r15/oQp/GLbeOUIwMqy+lau24AhWNDG)
            scope:
              - email
            redirect-uri: https://dev-server.meowzip.com/login/oauth2/code/google

# swagger
springdoc:
  packages-to-scan: com.meowzip.apiserver
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true

# aws config
cloud:
  aws:
    credentials:
      accessKey: ENC(FyBiJcHoxCgaL1BEil4FLZ3LJbYQiQBW2lwFU3GqTIM=)
      secretKey: ENC(5Luh7tlliBVQCvZmGVyzrqdblnDAb3gXBDlHgTIZa87lY1C1rwPQaLha32f5GYEsUU6g78X/OGg=)
    s3:
      bucket: meowzip-dev
      dir: images
    region: ap-northeast-2
    stack: false
    cloudfront:
      url: https://d2jzc2rxltjw7u.cloudfront.net

# encryption
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

# JWT
jwt:
  access-token:
    expiration: 60
    secret: ENC(m2+ZtoQy9Gt1yiM1uQh7z1J39KNyi6zx0i5pYEB+QoZ0IXWodaTIx3Iysn9mhMuXmGFw84ZwDktFQ6n33a3zlw==)
  refresh-token:
    expiration: 120
    secret: ENC(7zl2ombeG8gmT4uRIZ49LSBwG1QphYQWdM2iz5Os7/2hrZUEDUY6jxOYXkAIgTCIYKIWGuU80worlSNopUaCtw==)

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
  config: classpath:logback/logback-${spring.profiles.active}.xml

reset-password:
  validate-url: https://dev-server.meowzip.com/api/public/v1.0.0/members/reset-password/validate
  reset-url: http://localhost:3000/reset-pwd

# oauth2
oauth2:
  redirect-uri:
    google: https://localhost:3001/signin/google
    kakao: https://localhost:3001/signin/kakao

discord:
  webhook-url: https://discord.com/api/webhooks/1206174352207257610/I7HU-T2ZEMp43dDWMVyqjoY5Ke43AIM8b_JlxNt8juGzGZggbBWdGEces2smh2_4Lxg3