# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - "develop"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build With Gradle
        run: ./gradlew clean build --exclude-task test # 추후 테스트 제외 제거

      - name: Make Deploy Directory
        run: mkdir -p deploy

      - name: Copy Jar
        run: cp ./meowzip-api-server/build/libs/meowzip-api-server-0.0.1-SNAPSHOT.jar ./deploy

      - name: Copy Scripts
        run: cp -r ./scripts ./deploy

      - name: Add appspec.yml
        run: cp ./appspec-dev.yml ./deploy/appspec.yml

      - name: Make zip file
        run: zip -r ./meowzip.zip ./deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./meowzip.zip s3://meowzip-dev/dev-deploy/

      # Deploy
      - name: Run Meowzip Platform
        env:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
        run: aws deploy create-deployment 
              --application-name meowzip 
              --deployment-group-name meowzip-api-server-dev
              --file-exists-behavior OVERWRITE
              --s3-location bucket=meowzip-dev,bundleType=zip,key=dev-deploy/meowzip.zip